FROM mrjamesdickson/debug-with-tree:latest
COPY wrapup-command-script.sh /usr/local/bin/
LABEL org.nrg.commands="[{\"inputs\": [], \"name\": \"debug-tree-wrapup-command\", \"command-line\": \"wrapup-command-script.sh\", \"xnat\": [], \"image\": \"debug-tree-wrapup:latest\", \"version\": \"latest\", \"mounts\": [], \"type\": \"docker-wrapup\", \"description\": \"The debug wrapup command. Makes a file /output/wrapup-command-was-here with the contents being `find /input`.\"}]"

