FROM busybox:latest
COPY wrapup-command-script.sh /usr/local/bin/
LABEL org.nrg.commands="[{\"inputs\": [], \"name\": \"debug-wrapup-command\", \"command-line\": \"wrapup-command-script.sh\", \"xnat\": [], \"image\": \"xnat/debug-wrapup:1.0\", \"version\": \"1.0\", \"mounts\": [], \"type\": \"docker-wrapup\", \"description\": \"The debug wrapup command. Makes a file /output/wrapup-command-was-here with the contents being `find /input`.\"}]"
