FROM python:3.7.1-alpine3.8

RUN pip install --no-cache-dir \
        docopt \
        jsonpath \
        requests
COPY batch-launch.py /usr/local/bin
LABEL org.nrg.commands="[{\"inputs\": [{\"required\": true, \"name\": \"PROJECT\", \"user-settable\": false}, {\"required\": true, \"name\": \"SESSION_ID\", \"user-settable\": false}], \"name\": \"dcm2niix-scans-batch\", \"command-line\": \"batch-launch.py scans \$XNAT_HOST \$XNAT_USER \$XNAT_PASS dcm2niix-scan #SESSION_ID# #PROJECT#\", \"outputs\": [], \"image\": \"xnat/batch-launch:1.0\", \"override-entrypoint\": true, \"version\": \"1.0\", \"schema-version\": \"1.0\", \"xnat\": [{\"description\": \"Launch dcm2niix-scan on all scans in a session\", \"contexts\": [\"xnat:imageSessionData\"], \"name\": \"dcm2niix-scans-batch-session\", \"output-handlers\": [], \"label\": \"dcm2niix batch\", \"external-inputs\": [{\"load-children\": false, \"required\": true, \"type\": \"Session\", \"name\": \"session\", \"description\": \"Input session\"}], \"derived-inputs\": [{\"provides-value-for-command-input\": \"PROJECT\", \"name\": \"project\", \"derived-from-xnat-object-property\": \"project-id\", \"required\": true, \"user-settable\": false, \"derived-from-wrapper-input\": \"session\", \"type\": \"string\"}, {\"provides-value-for-command-input\": \"SESSION_ID\", \"name\": \"session-id\", \"derived-from-xnat-object-property\": \"id\", \"required\": true, \"user-settable\": false, \"derived-from-wrapper-input\": \"session\", \"type\": \"string\"}]}], \"mounts\": [], \"type\": \"docker\", \"description\": \"Launch dcm2niix containers on a batch of scans\"}, \
	{\"inputs\": [{\"required\": true, \"name\": \"PROJECT\", \"user-settable\": false}, {\"required\": true, \"name\": \"SUBJECT_ID\", \"user-settable\": false}], \"name\": \"dcm2niix-sessions-batch\", \"command-line\": \"batch-launch.py sessions \$XNAT_HOST \$XNAT_USER \$XNAT_PASS dcm2niix-scans-batch-session #SUBJECT_ID# #PROJECT#\", \"outputs\": [], \"image\": \"xnat/batch-launch:1.0\", \"override-entrypoint\": true, \"version\": \"1.0\", \"schema-version\": \"1.0\", \"xnat\": [{\"description\": \"Launch dcm2niix-scans-batch-session on all sessions in a subject\", \"contexts\": [\"xnat:subjectData\"], \"name\": \"dcm2niix-sessions-batch-subject\", \"output-handlers\": [], \"label\": \"dcm2niix batch\", \"external-inputs\": [{\"load-children\": false, \"required\": true, \"type\": \"Subject\", \"name\": \"subject\", \"description\": \"Input subject\"}], \"derived-inputs\": [{\"provides-value-for-command-input\": \"PROJECT\", \"name\": \"project\", \"derived-from-xnat-object-property\": \"project-id\", \"required\": true, \"user-settable\": false, \"derived-from-wrapper-input\": \"subject\", \"type\": \"string\"}, {\"provides-value-for-command-input\": \"SUBJECT_ID\", \"name\": \"subject-id\", \"derived-from-xnat-object-property\": \"id\", \"required\": true, \"user-settable\": false, \"derived-from-wrapper-input\": \"subject\", \"type\": \"string\"}]}], \"mounts\": [], \"type\": \"docker\", \"description\": \"Launch dcm2niix containers on a batch of sessions\"}, \
	{\"inputs\": [{\"required\": true, \"name\": \"PROJECT\", \"user-settable\": false}], \"name\": \"dcm2niix-subjects-batch\", \"command-line\": \"batch-launch.py subjects \$XNAT_HOST \$XNAT_USER \$XNAT_PASS dcm2niix-sessions-batch-subject #PROJECT# #PROJECT#\", \"outputs\": [], \"image\": \"xnat/batch-launch:1.0\", \"override-entrypoint\": true, \"version\": \"1.0\", \"schema-version\": \"1.0\", \"xnat\": [{\"description\": \"Launch dcm2niix-sessions-batch-subject on all subjects in a project\", \"contexts\": [\"xnat:projectData\"], \"name\": \"dcm2niix-subjects-batch-project\", \"output-handlers\": [], \"label\": \"dcm2niix batch\", \"external-inputs\": [{\"load-children\": false, \"required\": true, \"type\": \"Project\", \"name\": \"project\", \"description\": \"Input project\"}], \"derived-inputs\": [{\"provides-value-for-command-input\": \"PROJECT\", \"name\": \"project-id\", \"derived-from-xnat-object-property\": \"id\", \"required\": true, \"user-settable\": false, \"derived-from-wrapper-input\": \"project\", \"type\": \"string\"}]}], \"mounts\": [], \"type\": \"docker\", \"description\": \"Launch dcm2niix containers on a batch of subjects\"}]"
